[window]
startup_mode = "Maximized"
title = "Ubuntu Linux WSL2"
dynamic_title = true

[scrolling]
history = 100_000

[font]
size = 18

[font.normal]
family = "DroidSansM Nerd Font Mono"

[terminal]
shell = { program = 'C:\Windows\System32\wsl.exe', args = ["--cd ~"] }

[cursor.style]
shape = "Underline"
blinking = "On"

[mouse]
bindings = [
    { mouse = "Right", action = "Paste" },
]

[selection]
save_to_clipboard = true
